<!-- START of: finna - content/help-account_sv.phtml -->
<?php $this->headTitle($this->translate('tabs_help-account-instructions'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
    <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-account'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <h1>Anvisningar för inloggning</h1>
  <p>Med Finna.fi kan du hitta och använda material. Det är möjligt att använda tjänsten utan att vara inloggad, men som inloggad har du större nytta av Finna. Som inloggad användare kan du</p>
  <ul class="list-bullets">
    <li>kontrollera dina egna uppgifter</li>
    <li>reservera och förnya dina lån</li>
    <li>skapa listor med favoriter</li>
    <li>spara sökningar</li>
    <li>ställa in sökbevakning</li>
    <li>kommentera material.</li>
    </ul>
    <p>Det finns tre inloggningsalternativ:</p>
    <ul class="list-bullets">
      <li><a href="#finna-id-login">med Finna-användarnamn</a>, som kan skapas av alla användare</li>
      <li><a href="#haka-login">med en högskolas HAKA-användarnamn</a>, som är avsett särskilt för studenter och personal</li>
      <li><a href="#library-card-login">med bibliotekskort</a>.</li>
    </ul>
    <p><strong>Observera</strong> att konton som skapats med olika inloggningsalternativ är separata konton. Exempelvis favoritlistor som skapats med Finna-användarnamn kan inte användas på ett annat konto. Du kan dock flytta favoritlistor och sparade sökningar mellan olika konton. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#save-favourites">Se anvisningarna för favoritlistor</a>.</p>
   <div id="finna-id-login" class="content-section">
    <h2>Inloggning med Finna-användarnamn</h2>
    <p>Alla användare kan skapa ett Finna-användarnamn.</p>
    <p>Så här skapar du ett nytt Finna-användarnamn:</p>
    <ol class="list-numbers">
      <li>Logga in på ditt eget konto genom att i menyn uppe på sidan klicka på <strong>Logga in</strong>.</li>
      <li>Första gången du loggar in ska du skapa ett nytt Finna-användarnamn genom att klicka på <strong>Skapa nytt Finna-konto</strong> nere på inloggningssidan.
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-create_sv.png')?>" alt=""/></p></li>
      <li>Fyll i din e-postadress, önskat användarnamn och lösenord på blanketten. Klicka på <strong>Skicka</strong> efter att du fyllt i blanketten.
      <p class="text-muted"><small><strong>Tips!</strong>  Du kan till exempel använda din e-postadress som användarnamn, så är det lätt att komma ihåg.</small></p></li>
      <li>Ditt nya Finna-användarnamn har skapats och du kan genast använda tjänsten som inloggad användare. Du hittar ditt eget konto genom att klicka på ditt användarnamn uppe på sidan.</li>
    </ol>
    <h3>Har du redan ett Finna-användarnamn?</h3>
    <ol class="list-numbers">
      <li>Logga in på ditt eget konto genom att i menyn uppe på sidan klicka på <strong>Logga in</strong>.</li>
      <li>Fyll i ditt Finna-användarnamn och lösenord och klicka på <strong>Logga in</strong>.</li>
      <li>Nu kan du använda tjänsten som inloggad användare. Du hittar ditt eget konto genom att klicka på ditt användarnamn uppe på sidan.</li>
    </ol>
    <h3>Har du glömt lösenordet för ditt Finna-konto?</h3>
    <ol class="list-numbers">
      <li>Om du har glömt lösenordet för ditt konto kan du byta lösenord genom att klicka på <strong>Glömt ditt lösenord?</strong> i inloggningsvyn.
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-password_sv.png')?>" alt=""/></p></li>
      <li>Genom att klicka på länken öppnas en blankett där du kan fylla i ditt Finna-användarnamn eller din e-postadress. Välj sedan <strong>Återställ lösenordet</strong>.</li>
      <li>Du får anvisningar för att återställa lösenordet till den e-postadress som registrerats för ditt konto. Kontrollera skräpkorgen i din e-post om du väntat länge på meddelandet.</li>
    </ol>
  </div>
  <div id="haka-login" class="content-section">
    <h2>Inloggning med en högskolas HAKA-användarnamn</h2>
    <p>Högskolans HAKA-användarnamn är avsett särskilt för studenter och högskolans personal.</p>
    <p>Så här loggar du in:</p>
    <ol class="list-numbers">
      <li>Logga in på ditt eget konto genom att i menyn uppe på sidan klicka <strong>Logga in</strong>. Välj inloggningsalternativet <strong>HAKA login</strong> i menyn uppe på blanketten.</li>
      <li>Klicka på <strong>Haka Login</strong>. Inloggningsfönstret tar dig till inloggningssidan för din egen högskola. Fyll i blanketten för att återvända till Finna.fi som inloggad användare.</li>
      <li>Vid vissa högskolor är det möjligt att även ansluta den egna högskolans bibliotekskort till kontot. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#connect-library-card">Se anvisningen för att lägga till ett bibliotekskort</a>.</li>
    </ol>
  </div>
  <div id="library-card-login" class="content-section">
    <h2>Inloggning med bibliotekskort</h2>
    <p>Du kan även logga in på ditt eget konto med ditt bibliotekskort, om ditt bibliotek är medlem i Finna.</p> 
    <p>Så här loggar du in:</p>
    <ol class="list-numbers">
      <li>Logga in på ditt eget konto genom att i menyn uppe på sidan klicka på <strong>Logga in</strong>. Välj inloggningsalternativet <strong>Bibliotekskort</strong> uppe på blanketten.
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-login-library-card_sv.png')?>" alt=""/></p></li>
      <li>Välj ditt bibliotek i rullgardinsmenyn. 
      <p class="text-muted"><small><strong>Obs!</strong> Om du inte hittar ditt bibliotek i menyn, kan du inte logga in med bibliotekets kort. Du ska då välja ett annat inloggningsalternativ.</small></p></li>
      <li>Fyll sedan i ditt användarnamn eller streckkod (bibliotekskortets nummer) och ditt lösenord eller din pinkod. Klicka sedan på <strong>Logga in</strong>.</li>
      <li>Du har nu loggat in och kan börja ditt äventyr i materialskatternas värld.</li>
      <li>Då du loggar in ansluts bibliotekskortet i fråga till ditt konto, vilket gör att du får tillgång till bibliotekets tjänster. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#connect-library-card">. Det är även möjligt att ansluta flera bibliotekskort till kontot</a>.</li>
    </ol>
    <h3>Har du glömt ditt lösenord eller din pinkod?</h3>
    <p>Om du inte vet eller har glömt ditt användarnamn eller ditt lösenord/din pinkod ska du ta kontakt med ditt eget bibliotek. Vid högskolebiblioteken är ditt lösenord ditt eget efternamn, om du inte tidigare har skapat en egen pinkod.</p>
  </div>
</div>
<!-- END of: finna - content/help-account_sv.phtml -->
