<!-- START of: finna - Content/help-tabs.phtml -->
<?= $this->render('components/organisms/navigation/finna-multi-level-nav/finna-multi-level-nav.phtml',
  [
    'ariaLabel' => 'Ohjenavigaatio',
    'attributes' => [
      'class' => ['finna-multi-level-nav-content', 'finna-multi-level-nav-lg']
    ],
    'brandContent' => $this->translate('tabs_' . $activeTab),
    'collapseId' => 'nav-help-collapse',
    'items' => [
      [
        'active' => in_array($activeTab, ['help', 'help-basic', 'help-advanced']),
        'children' => [
          [
            'active' => 'help' === $activeTab,
            'label' => $this->translate('tabs_help'),
            'link' => $this->url('content-page', ['page' => 'help']),
          ],
          [
            'active' => 'help-basic' === $activeTab,
            'label' => $this->translate('tabs_help-basic'),
            'link' => $this->url('content-page', ['page' => 'help-basic']),
          ],
          [
            'active' => 'help-advanced' === $activeTab,
            'label' => $this->translate('tabs_help-advanced'),
            'link' => $this->url('content-page', ['page' => 'help-advanced']),
          ],
        ],
        'label' => $this->translate('tabs_help-search'),
        'link' => $this->url('content-page', ['page' => 'help'])
      ],
      [
        'active' => in_array($activeTab, ['help-account', 'help-account-management']),
        'children' => [
          [
            'active' => 'help-account' === $activeTab,
            'label' => $this->translate('tabs_help-account-instructions'),
            'link' => $this->url('content-page', ['page' => 'help-account']),
          ],
          [
            'active' => 'help-account-management' === $activeTab,
            'label' => $this->translate('tabs_help-account-management'),
            'link' => $this->url('content-page', ['page' => 'help-account-management']),
          ],
        ],
        'label' => $this->translate('tabs_help-account'),
        'link' => $this->url('content-page', ['page' => 'help-account']),
      ],
      [
        'active' => 'help-favorites' === $activeTab,
        'label' => $this->translate('tabs_help-favorites'),
        'link' => $this->url('content-page', ['page' => 'help-favorites']),
      ],
    ],
  ]);
?>
<!-- END of: finna - Content/help-tabs.phtml -->
