<!-- START of: finna - content/help-account_en-gb.phtml -->
<?php $this->headTitle($this->translate('tabs_help-account-instructions'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
    <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-account'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <h1>Instructions for logging in</h1>
  <p>Finna.fi enables you to both search and access resources. Finna can be used without logging in, but more functions are available to users who do. Once you have logged in, you can</p>
  <ul class="list-bullets">
    <li>Browse your information</li>
    <li>Reserve library material and renew your loans</li>
    <li>Create lists of favourites</li>
    <li>Save your searches</li>
    <li>Set alert schedules</li>
    <li>Comment on resources.</li>
    </ul>
    <p>There are three options for logging in:</p>
    <ul class="list-bullets">
      <li><a href="#finna-id-login">Finna ID</a> which is available to all users</li>
      <li><a href="#haka-login">A HAKA login from an institution of higher education</a>, primarily intended for students and staff</li>
      <li><a href="#library-card-login">A library card</a></li>
    </ul>
    <p><strong>Please note</strong> that accounts created with different login options are not connected to each other. For example, lists of favourites created with a Finna ID will not be available through your other accounts. However, it is possible to transfer lists of favourites and saved searches between accounts. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#save-favourites">See instructions for saving lists of favourites</a>.</p>
   <div id="finna-id-login" class="content-section">
    <h2>Log in with a Finna ID</h2>
    <p>All users may create a Finna ID.</p>
    <p>Creating a new Finna ID:</p>
    <ol class="list-numbers">
      <li>Log in to your account by selecting <strong>Login</strong> from the top menu bar.</li>
      <li>When you log in for the first time, you will have to create a Finna ID by by selecting <strong>Create New Finna ID</strong> at the bottom of the login window.
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-create_en-gb.png')?>" alt=""/></p></li>
      <li>Enter your email as well as your choice of username and password into the form. After you have completed the form, click on <strong>Submit</strong>.
      <p class="text-muted"><small><strong>Tip!</strong> Your email address is a good username, as it is easy to remember.</small></p></li>
      <li>Your new Finna ID has now been created and you can start using the service as a logged-in user. You can access your account by clicking on your username in the top menu bar.</li>
    </ol>
    <h3>Already have a Finna ID?</h3>
    <ol class="list-numbers">
      <li>Log in to your account by selecting <strong>Login</strong> from the top menu bar.</li>
      <li>Enter your Finna ID and password and select <strong>Login</strong>.</li>
      <li>You can now use the service as a logged-in user. You can access your account by clicking on your username in the top menu bar.</li>
    </ol>
    <h3>Forgotten the password for your Finna ID?</h3>
    <ol class="list-numbers">
      <li>If you have forgotten the password associated with your username, you may retrieve it by clicking on <strong>Forgot your password?</strong> at the bottom of the login window.
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-password_en-gb.png')?>" alt=""/></p></li>
      <li>The link will take you to a form requesting your Finna ID username or email address. After completing the form, click on <strong>Recover password</strong>.</li>
      <li>Instructions for recovering your password will be sent to the email address registered for your account. If the message is delayed, make sure to check your junk mail folder.</li>
    </ol>
  </div>
  <div id="haka-login" class="content-section">
    <h2>Using a HAKA login for institutions of higher education</h2>
    <p>The HAKA login is primarily intended for students and staff at institutions of higher education.</p>
    <p>How to log in:</p>
    <ol class="list-numbers">
      <li>Log in to your account by selecting Login from the top menu bar <strong>Login</strong>. Select the login option <strong>HAKA login</strong> from the top menu on the form.</li>
      <li>Click on <strong>Haka Login</strong>. The login window will take you to the login page for your institution. Complete the form and return to Finna.fi as a logged-in user.</li>
      <li>Some institutions of higher education enable users to add their library card for that institution’s library to the HAKA login. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#connect-library-card">Read the instructions for adding a library card</a>.</li>
    </ol>
  </div>
  <div id="library-card-login" class="content-section">
    <h2>Logging in with a library card</h2>
    <p>You can also log in to your account with your library card, if your library is a Finna partner organisation.</p>
    <p>How to log in:</p>
    <ol class="list-numbers">
      <li>Log in to your account by selecting <strong>Login</strong> from the top menu bar <strong>Login</strong>. Select the login option <strong>Library card</strong> from the tabs at the top of the form.
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-login-library-card_en-gb.png')?>" alt=""/></p></li>
      <li>Select your library from the drop-down menu.
      <p class="text-muted"><small><strong>NB!</strong> If your library is not listed, you cannot log in with a card from your library. Please choose another option for logging in.</small></p></li>
      <li>Enter your username or barcode (library card number) and your password or PIN code. Then select <strong>Login</strong>.</li>
      <li>You are now logged in and may begin to explore the treasure trove of Finnish museums, libraries and archives.</li>
      <li>The library card you used for logging in will be added to your account, which will also let you access the services of the library. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#connect-library-card">It is also possible to add several library cards to the account</a>. </li>
    </ol>
    <h3>Forgotten your password or PIN code?</h3>
    <p>If you do not know or have forgotten your username or password/PIN code, please contact your library. For libraries of institutions of higher education, the password is your last name, unless you have previously set your own PIN code.</p>
  </div>
</div>
<!-- END of: finna - content/help-account_en-gb.phtml -->
