<!-- START of: finna - Content/help-tabs.phtml -->
<?= $this->render('components/organisms/navigation/finna-multi-level-nav/finna-multi-level-nav.phtml',
  [
    'additionalClasses' => 'finna-multi-level-nav-content finna-multi-level-nav-lg',
    'ariaLabel' => 'Ohjenavigaatio',
    'brandContent' => $this->translate('tabs_' . $activeTab),
    'collapseId' => 'nav-help-collapse',
    'items' => [
      [
        'active' => in_array($activeTab, ['help', 'help-basic', 'help-advanced']),
        'children' => [
          [
            'active' => 'help' === $activeTab,
            'label' => $this->translate('tabs_help'),
            'link' => $this->url('content-page', ['page' => 'help']),
          ],
          [
            'active' => 'help-basic' === $activeTab,
            'label' => $this->translate('tabs_help-basic'),
            'link' => $this->url('content-page', ['page' => 'help-basic']),
          ],
          [
            'active' => 'help-advanced' === $activeTab,
            'label' => $this->translate('tabs_help-advanced'),
            'link' => $this->url('content-page', ['page' => 'help-advanced']),
          ],
        ],
        'label' => 'Hakuohjeet',
        'link' => $this->url('content-page', ['page' => 'help'])
      ],
      [
        'children' => [
          [
            'label' => 'Neuvoja kirjautumiseen',
            'link' => '',
          ],
          [
            'label' => 'Oman tilin hallinta',
            'link' => '',
          ],
        ],
        'label' => 'Kirjautuminen ja oma tili',
        'link' => ''
      ],
      [
        'active' => 'help-favorites' === $activeTab,
        'label' => $this->translate('tabs_help-favorites'),
        'link' => $this->url('content-page', ['page' => 'help-favorites']),
      ],
      [
        'label' => 'Aineistojen käyttö',
        'children' => [
          [
            'label' => 'Aineistojen käyttö',
            'link' => '',
          ],
          [
            'label' => 'CC-lisenssit',
            'link' => '',
          ],
        ],
        'link' => ''
      ],
      [
        'label' => 'Video-ohjeet',
        'children' => [
          [
            'label' => 'Haun tekeminen Finna.fi:ssä',
            'link' => '',
          ],
          [
            'label' => 'Suosikkilistojen luonti',
            'link' => '',
          ],
          [
            'label' => 'Kirjautuminen ja oma tilin hallinta',
            'link' => '',
          ],
          [
            'label' => 'Kirjastokortin liittäminen Finna-tiliin',
            'link' => '',
          ],
        ],
        'link' => ''
      ],
    ],
  ]);
?>
<!-- END of: finna - Content/help-tabs.phtml -->
