<!-- START of: finna - content/help-account_fi.phtml -->
<?php $this->headTitle($this->translate('tabs_help-account-instructions'))?>

<?php if ($this->resolver('content/help-tabs.phtml')): ?>
    <?=$this->render('content/help-tabs.phtml', ['activeTab' => 'help-account'])?>
<?php endif; ?>
<div class="sidebar left">
  <div class="content-navigation-menu">
  </div>
</div>
<div class="mainbody right">
  <h1>Neuvoja kirjautumiseen</h1>
  <p>Finna.fi-palvelussa voit löytää ja käyttää aineistoja. Voit käyttää palvelua, vaikka et kirjautuisi sisään palveluun. Kirjautuminen tuo kuitenkin enemmän mahdollisuuksia Finnan käyttöön. Jos kirjaudut palveluun, voit tehdä seuraavia asioita:</p>
  <ul class="list-bullets">
    <li>tarkastella omia tietojasi</li>
    <li>varata ja uusia lainojasi</li>
    <li>luoda suosikkilistoja</li>
    <li>tallentaa hakuja</li>
    <li>asettaa hakuvahteja</li>
    <li>kommentoida aineistoja</li>
  </ul>
  <p>Voit käyttää Finnaa monipuolisemmin, jos luot palveluun oman käyttäjätunnuksen. Sinulla on kolme eri vaihtoehtoa kirjautua palveluun</p>
  <ul class="list-bullets">
    <li><a href="#finna-id-login">Finna-tunnus</a>, jonka voivat luoda kaikki käyttäjät</li>
    <li><a href="#haka-login">Korkeakoulun HAKA-tunnus</a>, joka on tarkoitettu opiskelijoille ja henkilökunnalle</li>
    <li><a href="#library-card-login">Kirjastokortti</a></li>
  </ul>
  <p><strong>Huomioi</strong>, että eri kirjautumistavoilla luodut käyttäjätilit ovat erillisiä toisistaan. Esimerkiksi Finna-tunnuksella luodut suosikkilistat eivät ole käytettävissä toisessa tilissä. Voit kuitenkin siirtää suosikkilistoja ja tallennettuja hakuja tililtä toiselle. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#save-favourites">Katso ohjeet suosikkilistojen talteenotosta</a>.</p>
  <div id="finna-id-login" class="content-section">
    <h2>Finna-tunnuksella kirjautuminen</h2>
    <p>Finna-tunnuksen voivat luoda kaikki käyttäjät.</p>
    <p>Näin luot uuden Finna-tunnuksen:</p>
    <ol class="list-numbers">
      <li>Kirjaudu omaan tiliin valitsemalla ylävalikosta <strong>Kirjaudu</strong>.</li>
      <li>Valitse kirjautumisikkunan alaosasta <strong>Luo uusi Finna-tunnus</strong>.
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-create_fi.png')?>" alt=""/></p></li>
      <li>Täytä lomakkeeseen sähköpostiosoite, toivottu käyttäjänimi ja salasana. Jos käyttäjänimi on jo käytössä, sinun täytyy valita toinen. Kun olet täyttänyt lomakkeen, klikkaa <strong>Lähetä</strong>.
      <p class="text-muted"><small><strong>Vinkki!</strong> Voit laittaa käyttäjänimeksi esimerkiksi sähköpostiosoitteesi, jolloin se on helppo muistaa.</small></p></li>
      <li>Uusi Finna-tunnuksesi on valmis ja pääset heti käyttämään palvelua kirjautuneena käyttäjänä. Löydät oman tilisi, kun klikkaat sivun yläpalkista käyttäjänimeäsi.</li>
    </ol>
    <h3>Onko sinulla jo Finna-tunnus?</h3>
    <p>Jos sinulla on jo oma Finna-tunnus, voit kirjautua palveluun sen avulla.</p>
    <ol class="list-numbers">
      <li>Kirjaudu omaan tiliisi valitsemalla ylävalikosta <strong>Kirjaudu</strong>.</li>
      <li>Kirjoita Finna-tunnuksesi ja salasanasi. Valitse sitten <strong>Kirjaudu</strong>.</li>
      <li>Nyt olet kirjautunut palveluun ja voit käyttää sitä. Löydät oman tilisi klikkaamalla sivun yläpalkista käyttäjänimeäsi.</li>
    </ol>
    <h3>Oletko unohtanut Finna-tunnuksesi salasanan?</h3>
    <p>Jos olet unohtanut käyttäjätunnuksesi salasanan, voit vaihtaa sen tilalle uuden.</p>
    <ol class="list-numbers">
      <li>Avaa kirjautumisikkuna ja klikkaa <strong>Unohditko salasanasi?</strong>
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-password_fi.png')?>" alt=""/></p></li>
      <li>Linkistä pääset lomakkeelle, jonne voit kirjoittaa Finna-tunnuksesi käyttäjätunnuksen tai sähköpostiosoitteen. Valitse sen jälkeen <strong>Palauta salasana</strong>.</li>
      <li>Saat ohjeet salasanan palauttamiseen sähköpostiisi, jonka olet ilmoittanut käyttäjätunnuksellesi. Tarkistathan sähköpostisi roskapostikansion, jos viestin saapumisessa kestää.</li>
    </ol>
  </div>
  <div id="haka-login" class="content-section">
    <h2>Korkeakoulun HAKA-tunnuksella kirjautuminen</h2>
    <p>Korkeakoulun HAKA-tunnus on tarkoitettu opiskelijoille ja korkeakoulun henkilökunnalle.</p>
    <p>Näin kirjaudut palveluun HAKA-tunnuksella:</p>
    <ol class="list-numbers">
      <li>Kirjaudu omaan tiliin valitsemalla ylävalikosta <strong>Kirjaudu</strong>. Valitse lomakkeen ylävalikosta <strong>Korkeakoulun HAKA-tunnuksella</strong>.</li>
      <li>Klikkaa <strong>Haka Login</strong>. Kirjautumisikkuna vie sinut oman korkeakoulusi kirjautumissivulle. Täytä lomake, ja palaat takaisin Finna.fi-sivulle kirjautuneena käyttäjänä.</li>
      <li>Joissakin korkeakouluissa on mahdollista liittää tunnukseen myös oman korkeakoulun kirjastokortti. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#connect-library-card">Katso ohje kirjastokortin liittämiseen</a>.</li>
    </ol>
  </div>
  <div id="library-card-login" class="content-section">
    <h2>Kirjastokortilla kirjautuminen</h2>
    <p>Voit kirjautua omaan tiliisi kirjastokortilla, jos kirjastosi on mukana Finnassa.</p>
    <p>Näin kirjaudut palveluun kirjastokortilla:</p>
    <ol class="list-numbers">
      <li>Kirjaudu omaan tiliin valitsemalla ylävalikosta <strong>Kirjaudu</strong>. Valitse lomakkeen ylävalikosta <strong>Kirjastokortilla</strong>.
      <p class="hidden-xs"><img src="<?=$this->imageLink('help-account-login-library-card_fi.png')?>" alt=""/></p></li>
      <li>Valitse kirjastosi valikosta. 
      <p class="text-muted"><small><strong>Huomio!</strong> Jos et löydä kirjastoasi valikosta, et voi kirjautua sisään kirjastokortillasi. Valitse tällöin toinen kirjautumistapa.</small></p></li>
      <li>Kirjoita seuraavaksi käyttäjätunnus tai viivakoodi. Viivakoodi on numero, jonka löydät kirjastokortistasi. Kirjoita kirjastokorttisi salasana tai PIN-koodi. Valitse sen jälkeen <strong>Kirjaudu</strong>.</li>
      <li>Olet kirjautunut sisään ja voit alkaa etsiä kiinnostavia aineistoja.</li>
      <li>Kirjautumisen yhteydessä tiliisi liitetään kyseinen kirjastokortti, jolloin saat käyttöösi kirjaston palveluja. <a href="<?=$this->url('content-page', ['page' => 'help-account-management'])?>#connect-library-card">Voit liittää tiliisi useita kirjastokortteja</a>, jos haluat.</li>
    </ol>
    <h3>Oletko unohtanut kirjastokorttisi salasanan tai PIN-koodin?</h3>
    <p>Ota yhteyttä omaan kirjastoosi, jos et tiedä tai olet unohtanut käyttäjätunnuksesi tai salasanasi/PIN-koodisi. Korkeakoulujen kirjastoissa salasana on aina oma sukunimi, jos käyttäjä ei ole asettanut PIN-koodia aiemmin.</p>
  </div>
</div>
<!-- END of: finna - content/help-account_fi.phtml -->
