<?php $collapsed = $collapsed ?? true; ?>
<div<?= $this->attributes($attributes ?? [])->add('class', ['finna-panel', 'panel']) ?>>
  <?php if (isset($heading)): ?>
    <div<?= $this->attributes(isset($headingId) ? ['id' => $headingId] : [])->add('class', 'panel-heading') ?>>
      <?php if (isset($titleHeadingLevel)): ?>
        <h<?= $titleHeadingLevel ?> class="panel-title">
      <?php endif; ?>
          <?php
            if (isset($collapseId)) {
              $headingInnerElement = 'a';
              $headingInnerAttributes = $this->attributes([
                'role' => 'button',
                'data-toggle' => 'collapse',
                'href' => '#' . $collapseId,
                'aria-expanded' => $collapsed ? 'false' : 'true',
                'aria-controls' => $collapseId
              ]);
              if ($collapsed) {
                $headingInnerAttributes->add('class', 'collapsed');
              }
            }
            else {
              $headingInnerElement = 'span';
              $headingInnerAttributes = $this->attributes();
            }
          ?>
          <<?= $headingInnerElement ?><?= $headingInnerAttributes->add('class', 'finna-panel-heading-inner') ?>>
            <?= $heading ?>
          </<?= $headingInnerElement ?>>
      <?php if (isset($titleHeadingLevel)): ?>
        </h<?= $titleHeadingLevel ?>>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <?php if (isset($collapseId)): ?>
    <?php
      $collapseAttributes = $this->attributes([
        'id' => $collapseId,
        'class' => ['panel-collapse', 'collapse'],
        'aria-labelledby' => $headingId,
      ]);
      if (!$collapsed) {
        $collapseAttributes->add('class', 'in');
      }
    ?>
    <div<?= $collapseAttributes ?>>
  <?php endif; ?>
      <div class="panel-body">
        <?= $content ?>
      </div>
  <?php if (isset($collapseId)): ?>
    </div>
  <?php endif; ?>
  <?php if (isset($footer)): ?>
    <div class="panel-footer">
      <?= $footer ?>
    </div>
  <?php endif; ?>
</div>
