<?php //Don't add START and END comments ?>
<?php if(!empty($data)): ?>
  <div class="truncate-field">
    <?php foreach ($data as $index => $item): ?>
      <?php
        $additional = [];
        if (!empty($item['method'])) {
          $additional[] = $this->escapeHtml($item['method']);
        }
        if (!empty($item['date'])) {
          $additional[] = $this->escapeHtml($item['date']);
        }
      ?>
      <?=$index > 0 ? '<br/>' : '' ?><?=$this->record($this->driver)->getAuthorityLinkElement('author', $item['name'], $item, ['role' => true, 'authorityType' => $item['type'] ?? null, 'showInlineInfo' => true])?><?php if (!empty($additional)): ?>, <?=implode(' ', $additional) ?><?php endif; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
