<!-- START of: finna - Recommend/OntologyDeferred.phtml -->
<?php
  // Set up Javascript for use below:
  $loadJs = 'var url = VuFind.path + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
    . "\$('#ontology-recommendations-deferred').load(url);";
?>
<div id="ontology-recommendations-deferred">
  <p><i class="fa fa-spinner fa-spin" aria-hidden="true"></i> <?=$this->transEsc("Loading")?>...</p>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>
<!-- END of: finna - Recommend/OntologyDeferred.phtml -->
