<!-- START of: finna - Recommend/Ontology.phtml -->
<?php if (!empty($ontologyResults = $this->recommend->getOntologyResults())): ?>
  <?php foreach ($ontologyResults as $type => $typeResults): ?>
    <?php foreach ($typeResults as $term => $termResults): ?>
      <div class="ontology-recommendation ontology-<?= $type ?> alert alert-info">
        <p><?= $this->transEsc(
          'ontology_recommendation_' . $type,
          ['%%term%%' => $term, '%%results_count%%' => count($termResults)]
        ) ?>
        <?php if (1 === count($termResults)): ?>
          <a href="<?= $termResults[0]['href'] ?>" data-key="<?= $termResults[0]['key'] ?>" data-value="<?= $termResults[0]['value'] ?>">'<?= $termResults[0]['label'] ?>'</a>
          </p>
        <?php else: ?>
          </p>
          <ul<?php if (count($termResults) > 5):?> class="truncate-field" data-rows="1"<?php endif;?>>
            <?php foreach ($termResults as $termResult): ?>
              <li><a href="<?= $termResult['href'] ?>" data-key="<?= $termResult['key'] ?>" data-value="<?= $termResult['value'] ?>"><?= $termResult['label'] ?></a></li>
            <?php endforeach; ?>
          </ul>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  <?php endforeach; ?>
  <?php
    $script = <<<EOT
    $('.ontology-recommendation a').each(function() {
      $(this).click(function() {
        $.cookie($(this).data('key'), $(this).data('value'), {path: VuFind.path});
      });
    });
EOT;
    echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
  ?>
<?php endif; ?>
<!-- END of: finna - Recommend/Ontology.phtml -->
