<?php
  $attributes = $this->htmlAttributes($attributes ?? []);
  $attributes['aria-label'] = $ariaLabel;
?>
<nav<?= $attributes->add('class', 'finna-tabs-nav') ?>>
  <?php
    $__navAttributes = $this->htmlAttributes(['class' => 'nav-tabs']);
    if ($attributes->hasValue('class', 'finna-tabs-nav-lg')) {
      $__navAttributes->add('class', 'finna-nav-lg');
    }
  ?>
  <?= $this->render('components/molecules/navigation/finna-nav/finna-nav.phtml', [
      'attributes' => $__navAttributes,
      'items' => $items,
      'renderChildren' => 'simple'
    ]); ?>
</nav>
<?php $this->headScript()->appendFile('components/organisms/navigation/finna-tabs-nav/finna-tabs-nav.js'); ?>
