<!-- START of: finna - RecordDriver/DefaultRecord/core-field-groups.phtml -->
<?php foreach ($data as $key => $current): ?>
  <?php $header = $this->transEsc($current['context']['title'] ?? $current['label']); ?>
  <?php if ($header): ?>
    <?php if ($class = $current['context']['class'] ?? null): ?>
      <tr class="<?=$this->escapeHtmlAttr($class)?>">
    <?php else: ?>
      <tr>
    <?php endif; ?>
        <th colspan="2"><?=$header?></th>
      </tr>
      <?=$current['value']?>
  <?php else: ?>
    <?=$current['value']?>
  <?php endif; ?>
<?php endforeach; ?>
<!-- END of: finna - RecordDriver/DefaultRecord/core-field-groups.phtml -->
